<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INWS03011-02" ignored="0" name="Groups Test" tests="5" failures="1" timestamp="04 Jun 2021 12:30:06 GMT" time="0.064" errors="0">
  <testcase name="test" time="0.016" classname="com.project.test.group.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.project.test.group.LoginTest.test(LoginTest.java:10)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="APISubTest1_2" time="0.015" classname="com.project.test.group.APITestCases1"/>
  <testcase name="APITestCase2" time="0.0" classname="com.project.test.group.APITestCases2"/>
  <testcase name="APISubTest1_0" time="0.0" classname="com.project.test.group.APITestCases1">
    <skipped/>
  </testcase> <!-- APISubTest1_0 -->
  <testcase name="APITestCase1" time="0.0" classname="com.project.test.group.APITestCases1">
    <skipped/>
  </testcase> <!-- APITestCase1 -->
</testsuite> <!-- Groups Test -->
